name: ltpp
description: 'LTPP在线开发平台'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <=3.10.5'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  shared_preferences: ^2.0.17
  event_bus: ^2.0.0
  path_provider: ^2.0.15
  video_player: ^2.6.1
  chewie: ^1.5.0
  flutter_widget_from_html: ^0.10.1
  webview_flutter: ^4.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - images/
    - images/dbimage/
    - images/default/
